import streamlit as st
from openai import OpenAI
import pandas as pd
import PyPDF2
from docx import Document
from fpdf import FPDF
from duckduckgo_search import DDGS
from pptx import Presentation
from ics import Calendar, Event
import base64
import io
import zipfile
import json
from datetime import datetime, timedelta

# --- 1. SYSTEM CONFIGURATION ---
st.set_page_config(page_title="Studio V20: Sentient HQ", layout="wide", page_icon="🧠")

st.markdown("""
    <style>
    .stButton button {height: 3.5em; font-weight: 800; border-radius: 8px; background-color: #0E1117; color: white; border: 1px solid #303030;}
    .brand-sidebar {background-color: #f8f9fa; padding: 15px; border-radius: 10px;}
    div[data-testid="stStatusWidget"] {visibility: visible;}
    </style>
    """, unsafe_allow_html=True)

# --- 2. AUTHENTICATION ---
if "OPENAI_API_KEY" in st.secrets:
    api_key = st.secrets["OPENAI_API_KEY"]
else:
    api_key = st.sidebar.text_input("🔑 API Key", type="password")
    if not api_key: st.stop()

client = OpenAI(api_key=api_key)

if "history" not in st.session_state: st.session_state.history = []

# --- 3. THE ARTIFACT ENGINES ---

def create_ics(events_data):
    """Generates a real Calendar file."""
    c = Calendar()
    for e in events_data:
        event = Event()
        event.name = e.get('summary', 'Project Task')
        event.begin = e.get('date', datetime.now().strftime("%Y-%m-%d"))
        event.description = e.get('desc', 'Generated by Studio V20')
        c.events.add(event)
    return str(c).encode('utf-8')

def create_audio(text):
    """The Orator: Generates HD Speech."""
    response = client.audio.speech.create(
        model="tts-1",
        voice="onyx",
        input=text[:4096] # Limit for API
    )
    return response.content

def create_pptx(slides_content):
    prs = Presentation()
    for slide_data in slides_content:
        layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(layout)
        slide.shapes.title.text = slide_data.get('title', 'Untitled')
        slide.placeholders[1].text = slide_data.get('body', '')
    out = io.BytesIO()
    prs.save(out)
    return out.getvalue()

def create_pdf(text):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_font("Arial", size=12)
    safe_text = text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, safe_text)
    return pdf.output(dest="S").encode("latin-1")

def web_search(query):
    try:
        results = DDGS().text(query, max_results=3)
        return "\n".join([f"- {r['title']}: {r['body']}" for r in results])
    except: return "Web search offline."

# --- 4. THE SENTIENT SWARM (Self-Correcting) ---

def run_sentient_swarm(protocol, mission, context, image_data=None):
    results = {}
    
    with st.status("🧠 Sentient HQ: Initializing...", expanded=True) as status:
        
        # 1. LIVE INTEL
        status.write("🌍 Agent 1: Scanning Global Intel...")
        intel = web_search(f"{mission} trends stats")
        
        # 2. DRAFTING PHASE
        status.write("✍️ Agent 2: Drafting Strategy...")
        full_context = f"MISSION: {mission}\nINTEL: {intel}\nCONTEXT: {context}"
        
        draft_resp = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "system", "content": f"Execute {protocol}. Context: {full_context}. Output Markdown."}]
        )
        draft_text = draft_resp.choices[0].message.content
        
        # 3. RED TEAM PHASE (The SOTA Feature)
        status.write("🛡️ Agent 3: Red Team Critique (Self-Correction)...")
        critique_resp = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "user", "content": draft_text},
                {"role": "system", "content": "CRITIQUE MODE. Identify 3 weak points, logical gaps, or missing risks in this strategy. Be harsh."}
            ]
        )
        critique = critique_resp.choices[0].message.content
        
        # 4. FINAL POLISH
        status.write("💎 Agent 4: Finalizing Master Strategy...")
        final_resp = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "assistant", "content": draft_text},
                {"role": "user", "content": f"Apply this critique to perfect the strategy: {critique}"}
            ]
        )
        results['Master_Strategy.md'] = final_resp.choices[0].message.content
        
        # 5. ARTIFACT GENERATION (Calendar & Audio)
        status.write("📅 Agent 5: Generating Timeline & Audio...")
        
        # Calendar Extraction
        cal_prompt = f"Extract key dates/deadlines from this strategy into JSON: [{{'summary': '...', 'date': 'YYYY-MM-DD', 'desc': '...'}}]. \nSTRATEGY: {results['Master_Strategy.md'][:3000]}"
        try:
            cal_resp = client.chat.completions.create(
                model="gpt-4o", response_format={ "type": "json_object" },
                messages=[{"role": "system", "content": cal_prompt}]
            )
            cal_json = json.loads(cal_resp.choices[0].message.content)
            results['Production_Schedule.ics'] = create_ics(cal_json.get('events', []))
        except: pass

        # Audio Briefing
        results['Audio_Briefing.mp3'] = create_audio(f"Here is your briefing for {mission}. {results['Master_Strategy.md'][:1000]}")
        
        # PPTX (If needed)
        if "Presentation" in protocol:
            slide_prompt = f"Convert to 5 slides JSON: [{{'title': '...', 'body': '...'}}]. \nTEXT: {results['Master_Strategy.md'][:2000]}"
            slide_resp = client.chat.completions.create(
                model="gpt-4o", response_format={ "type": "json_object" },
                messages=[{"role": "system", "content": slide_prompt}]
            )
            slides_json = json.loads(slide_resp.choices[0].message.content)
            results['Executive_Deck.pptx'] = create_pptx(slides_json.get('slides', []))

        status.update(label="✅ Sentient Cycle Complete", state="complete")
        
    return results

# --- 5. INTERFACE ---
with st.sidebar:
    st.title("🧬 Brand DNA")
    brand_name = st.text_input("Org Name", placeholder="Apex Media")
    north_star = st.text_area("North Star Goal", placeholder="Growth...")

st.title("🧠 Studio V20: Sentient HQ")

col1, col2 = st.columns([2, 1])
with col1:
    mission_input = st.text_area("Mission Objective", placeholder="e.g. Launch Q3 Campaign...", height=100)
    uploaded_file = st.file_uploader("Intel", type=["pdf", "docx", "txt"])
with col2:
    protocol = st.selectbox("Protocol:", [
        "💼 Executive Strategy Presentation (.pptx)",
        "🚀 Full Product Launch (.ics + .pdf)",
        "📢 Crisis Response Suite",
        "🎥 Video Production Bible"
    ])
    if st.button("🚀 INITIATE", type="primary", use_container_width=True):
        if not mission_input: st.stop()
        context = f"Brand: {brand_name}. Goal: {north_star}."
        outputs = run_sentient_swarm(protocol, mission_input, context)
        st.session_state.history.insert(0, outputs)
        st.rerun()

# --- 6. OUTPUTS ---
if st.session_state.history:
    st.divider()
    latest = st.session_state.history[0]
    
    # AUDIO PLAYER
    if 'Audio_Briefing.mp3' in latest:
        st.subheader("🎧 Audio Briefing")
        st.audio(latest['Audio_Briefing.mp3'])
    
    # PREVIEW
    if 'Master_Strategy.md' in latest:
        with st.expander("📄 Read Strategy", expanded=True):
            st.markdown(latest['Master_Strategy.md'])
    
    # DOWNLOADS
    col_a, col_b = st.columns(2)
    
    # Bundle Download
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED, False) as zip_file:
        for key, val in latest.items():
            if key.endswith(('.pptx', '.mp3', '.ics')):
                zip_file.writestr(key, val)
            elif key.endswith('.md'):
                zip_file.writestr(key, val)
                try: zip_file.writestr(key.replace('.md', '.pdf'), create_pdf(val))
                except: pass
    
    with col_a:
        st.download_button("📦 Download Full Bundle (.ZIP)", zip_buffer.getvalue(), "Sentient_Bundle.zip", "application/zip", type="primary", use_container_width=True)
        
    with col_b:
        if 'Production_Schedule.ics' in latest:
            st.download_button("📅 Add to Calendar (.ics)", latest['Production_Schedule.ics'], "schedule.ics", "text/calendar", use_container_width=True)
